site_name: Welcome to PyPDFForm - PyPDFForm Documentation
repo_url: https://github.com/chinapandaman/PyPDFForm
nav:
  - 'User Guide':
    - install.md
    - coordinate.md
    - prepare.md
    - inspect.md
    - fill.md
    - simple_fill.md
    - style.md
    - button_style.md
    - draw.md
    - utils.md
  - 'Developer Guide':
    - dev_intro.md
    - dev_changes.md
    - dev_doc.md
    - dev_test.md
    - dev_release.md
theme:
  name: readthedocs
  logo: img/logo.png
extra:
  version: v2.2.1
